Layout/AlignHash:
  EnforcedColonStyle: table

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Variable

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 310

Metrics/ClassLength:
  Max: 226

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 226
